In [1]:
import numpy as np
from scipy.linalg import schur, eigvals

# Exercise 1

$$
A 
= 
\begin{pmatrix}
    5 & 5 & 0 & 4 \\
    1 & 1 & 5 & 0 \\
    3 & 2 & 0 & 4 \\
    5 & 3 & 0 & 5 \\
    0 & 0 & 4 & 0 
\end{pmatrix}
$$

## a. 
Compute the SVD of the matrix A.

In [2]:
A = np.array([[5,5,0,4], [1,1,5,0], [3,2,0,4], [5,3,0,5], [0,0,4,0]])

In [24]:
print(A)

[[5 5 0 4]
 [1 1 5 0]
 [3 2 0 4]
 [5 3 0 5]
 [0 0 4 0]]


In [3]:
U, S, Vt = np.linalg.svd(A)
print(f'U = {np.around(U,2)}')
print(f'V^T = {np.around(Vt,2)}')
print(f'Sigma = {np.around(S,2)}')

U = [[-0.65  0.04  0.71  0.23  0.15]
 [-0.11 -0.78  0.14 -0.24 -0.55]
 [-0.43  0.06 -0.51  0.63 -0.4 ]
 [-0.62  0.07 -0.41 -0.64  0.2 ]
 [-0.02 -0.62 -0.22  0.31  0.69]]
V^T = [[-0.63 -0.49 -0.05 -0.6 ]
 [-0.01 -0.04 -0.99  0.12]
 [ 0.05  0.75 -0.11 -0.66]
 [-0.78  0.45  0.04  0.44]]
Sigma = [12.32  6.42  1.92  0.53]


## b.
The largest singular values give us information about stereotypical groups/types of viewers. 
What types can you find if you look at $Av_1 = \sigma_1 u_1$ and $Av_2 = \sigma_2 u_2$, respectively? 

### Answer:

In [4]:
np.round(S[0]*np.outer(U[:,0], Vt[0,:]))

array([[5., 4., 0., 5.],
       [1., 1., 0., 1.],
       [3., 3., 0., 3.],
       [5., 4., 0., 5.],
       [0., 0., 0., 0.]])

From $Av_1 = \sigma_1 u_1$, we can discern the following information,

|         | Drama 1 | Drama 2 | Sci-Fi | Documentary |
|---------|---------|---------|--------|-------------|
| Ali     | 5       | 4       | 0      | 5           |
| Beatrix | 1       | 1       | 0      | 1           |
| Elsa    | 3       | 3       | 0      | 3           |
| Johan   | 5       | 4       | 0      | 5           |
| Chandra | 0       | 0       | 0      | 0           |

We see that the first category is correct with respect to the original matrix $A$, whereas categories 2 and 4 are somewhat skewed towards the values of the first category. This specific preference pattern is the strongest one from matrix $A$ and "pulls" the other two categories in the same direction in this submatrix. The pattern in column 3 is completely lost here, presumably because it deviates so strongly from the dominating pattern.

In [5]:
np.round(S[1]*np.outer(U[:,1], Vt[1,:]))

array([[-0., -0., -0.,  0.],
       [ 0.,  0.,  5., -1.],
       [-0., -0., -0.,  0.],
       [-0., -0., -0.,  0.],
       [ 0.,  0.,  4., -0.]])

From $Av_2 = \sigma_2 u_2$, we can discern the following information

|         | Drama 1 | Drama 2 | Sci-Fi | Documentary |
|---------|---------|---------|--------|-------------|
| Ali     | 0       | 0       | 0      | 0           |
| Beatrix | 0       | 0       | 5      | -1          |
| Elsa    | 0       | 0       | 0      | 0           |
| Johan   | 0       | 0       | 0      | 0           |
| Chandra | 0       | 0       | 4      | 0           |

Here we mainly get the information from column 3, which is correct with respect to the original matrix $A$. We also get a slight correction with respect to the fourth column, which was affected too much from the first submatrix.

It should be noted here that the values have been rounded to 0 decimals. Had we kept more decimals then we would have seen that most values are adjusted by at least a few decimal points in the second submatrix. 

## c.
Try to interpret the column space $\mathbf{C}(A)$ and the row space $\mathbf{C}(A^T)$ here. What dimensions 
and what does it mean in relation to stereotypical viewers and movie categories respectively?

### Answer:

In [6]:
np.linalg.matrix_rank(A)

4

$A$ is a $5 \times 4$ matrix of rank 4. We have that 
$$V \in \mathbb{R}^N = \mathbb{R}^4,$$ 
$$U \in \mathbb{R}^M = \mathbb{R}^5,$$
where
$$v_1, \ldots, v_4 \in \mathbf{C}(A^T),$$
$$u_1, \ldots, u_4 \in \mathbf{C}(A),$$
$$u_5 \in \mathbf{N}(A^T).$$

# Exercise 2

In [7]:
def eigen(B):
    iterations = 0
    converged = False
    Q = np.identity(B.shape[0]) # Assumes that B is a square matrix
    while not converged:
        Q_temp, R = np.linalg.qr(B)
        B_new = R @ Q_temp
        Q = Q @ Q_temp
        print(B)
        if (np.abs(B - B_new) <= 0.0001).all() or iterations > 50: # Had to add limit for experiment b
            converged = True
        B = B_new
        iterations += 1
    return B, Q

## a.
Choose a symmetric matrix, for example
$$
B =
\begin{pmatrix}
    3 & 1 & 3 & 1 \\
    1 & 5 & 3 & 1 \\
    3 & 3 & 6 & 3 \\
    1 & 1 & 3 & 2 
\end{pmatrix}
$$
First, use the built-in function in Python to compute the eigenvalues and
eigenvectors. “Save” them somewhere, so that you easily can compare with your
results.
Run your program until you can see the eigenvalues. What seems to happen
gradually when you run your algorithm?

In [8]:
B = np.array([[3, 1, 3, 1], [1, 5, 3, 1], [3, 3, 6, 3], [1, 1, 3, 2]])

In [9]:
v, w = np.linalg.eig(B)
print(f'eigenvalues: {v}')
print(f'normalized eigenvectors: \n{w}')

eigenvalues: [10.96432189  3.36342138  1.5685288   0.10372793]
normalized eigenvectors: 
[[ 0.37332619  0.39736239 -0.76974669  0.33199505]
 [ 0.48053726 -0.85106908 -0.13659365  0.16157828]
 [ 0.71896427  0.25541561  0.21809441 -0.608513  ]
 [ 0.3358599   0.22923224  0.58418065  0.70241275]]


In [10]:
B, Q = eigen(B)

[[3 1 3 1]
 [1 5 3 1]
 [3 3 6 3]
 [1 1 3 2]]
[[ 9.60000000e+00  2.57289681e+00  1.76610166e+00 -3.29690237e-02]
 [ 2.57289681e+00  4.25858586e+00  1.77499895e-01 -3.31351155e-03]
 [ 1.76610166e+00  1.77499895e-01  2.03271849e+00 -9.39491871e-02]
 [-3.29690237e-02 -3.31351155e-03 -9.39491871e-02  1.08695652e-01]]
[[ 1.08724239e+01  7.97930561e-01  2.88178342e-01  3.39307937e-04]
 [ 7.97930561e-01  3.41508015e+00 -2.11247995e-01 -2.48728342e-04]
 [ 2.88178342e-01 -2.11247995e-01  1.60874826e+00  5.42644827e-03]
 [ 3.39307937e-04 -2.48728342e-04  5.42644827e-03  1.03747637e-01]]
[[ 1.09568113e+01  2.36433617e-01  4.17639696e-02 -3.22736500e-06]
 [ 2.36433617e-01  3.36354879e+00 -1.12423644e-01  8.68768316e-06]
 [ 4.17639696e-02 -1.12423644e-01  1.57591194e+00 -3.53609539e-04]
 [-3.22736500e-06  8.68768316e-06 -3.53609539e-04  1.03728011e-01]]
[[ 1.09636397e+01  7.18435156e-02  5.98679879e-03  3.05460721e-08]
 [ 7.18435156e-02  3.36252358e+00 -5.31216077e-02 -2.71039082e-07]
 [ 5.98679879e

In [11]:
print(f'B: {B}')
print(f'Q: {Q}')

B: [[ 1.09643219e+01  1.72328414e-06  1.50313924e-10 -2.14708355e-16]
 [ 1.72328414e-06  3.36342138e+00 -5.55260376e-05  5.23527538e-16]
 [ 1.50314724e-10 -5.55260376e-05  1.56852881e+00 -6.04243265e-16]
 [-1.85438574e-26  6.85007360e-21 -5.63605111e-16  1.03727926e-01]]
Q: [[-0.37332628  0.39738612  0.7697344   0.33199505]
 [-0.48053707 -0.85106496  0.13661998  0.16157828]
 [-0.71896433  0.2554087  -0.21810231 -0.608513  ]
 [-0.33585995  0.22921409 -0.58418774  0.70241275]]


### Answer:
We see that the B matrix converges towards a matrix where the eigenvalues occupy the main diagonal and all other entries are zero.

The Q matrix contains the normalized eigenvectors of the original B matrix. Some of the vectors have flipped signs, but this does not change the property that it is still an eigenbasis.

## b. 
Repeat the same experiment with a non-symmetric matrix, for example
$$
B =
\begin{pmatrix}
    2 & 1 & 0 & 0 \\
    2 & 3 & 1 & 1 \\
    2 & 2 & 1 & 1 \\
    1 & 2 & 2 & 5 
\end{pmatrix}
$$
What did the end-result look like here?
(What you hopefully see here is the so-called Schur decomposition. You can look
it up, i.e. in Wikipedia, if you haven’t heard of it in linear algebra before).

In [12]:
B = np.array([[2, 1, 0, 0], [2, 3, 1, 1], [2, 2, 1, 1], [1, 2, 2, 5]])

In [13]:
T, Z = schur(B)

In [14]:
v, w = np.linalg.eig(B)
print(f'eigenvalues: {v}')
print(f'normalized eigenvectors: \n{w}')

eigenvalues: [6.65081185 3.14482996 0.87741251 0.32694568]
normalized eigenvectors: 
[[ 0.07909278 -0.32011776  0.65430026  0.24539445]
 [ 0.36784562 -0.3664804  -0.73450929 -0.41055825]
 [ 0.31253724 -0.24994615  0.1026218   0.84518017]
 [ 0.87221236  0.83710433  0.14783791 -0.23852457]]


In [15]:
B, Q = eigen(B)

[[2 1 0 0]
 [2 3 1 1]
 [2 2 1 1]
 [1 2 2 5]]
[[ 5.76923077  0.6863214  -0.07924957 -1.82087393]
 [ 2.63297845  2.38866397  1.45623165 -0.07924957]
 [ 1.44810575  1.63387789  2.53441296 -0.2121357 ]
 [-0.26646936 -0.51872445 -0.69879997  0.30769231]]
[[ 6.8784029  -0.70809259  0.38270072  1.5506482 ]
 [ 1.46108439  2.78598952  0.53868294 -1.31404976]
 [ 0.28736062  0.70051529  1.02165409 -0.0084497 ]
 [ 0.01324083  0.06175166  0.04577972  0.31395349]]
[[ 6.88465062e+00 -1.41603552e+00  6.52193363e-01 -1.23760583e+00]
 [ 6.38684982e-01  2.93114609e+00 -1.17668073e-01  1.62828413e+00]
 [ 3.59981544e-02  2.13176360e-01  8.51716449e-01 -3.03014321e-01]
 [-6.26072308e-04 -6.96464913e-03 -1.17899910e-02  3.32486842e-01]]
[[ 6.78296843e+00 -1.72131203e+00  7.48194027e-01  1.07651905e+00]
 [ 2.81646875e-01  3.02400065e+00 -3.59402121e-01 -1.71126250e+00]
 [ 4.51076438e-03  6.25443940e-02  8.62637636e-01  4.13503402e-01]
 [ 2.99192464e-05  7.63865267e-04  4.61607098e-03  3.30393285e-01]]
[[ 6.71

In [16]:
print(B)
print(Q)

[[ 6.65081185e+00 -1.98074294e+00  7.74005985e-01  9.35635062e-01]
 [ 6.35208293e-17  3.14482996e+00 -4.96916395e-01 -1.77347324e+00]
 [ 2.56726831e-45  1.63453318e-28  8.77412506e-01  4.58285872e-01]
 [ 4.55544508e-68  5.23678706e-51  1.27777033e-23  3.26945677e-01]]
[[ 0.07909278 -0.41235751  0.76596251  0.48683371]
 [ 0.36784562 -0.62874169 -0.59373444  0.34183754]
 [ 0.31253724 -0.4636485   0.22524291 -0.79788231]
 [ 0.87221236  0.46869526  0.10023215  0.0975903 ]]


In [17]:
print(T)
print(Z)

[[ 6.65081185 -1.98074294  0.77400599 -0.93563506]
 [ 0.          3.14482996 -0.49691639  1.77347324]
 [ 0.          0.          0.87741251 -0.45828587]
 [ 0.          0.          0.          0.32694568]]
[[ 0.07909278 -0.41235751  0.76596251 -0.48683371]
 [ 0.36784562 -0.62874169 -0.59373444 -0.34183754]
 [ 0.31253724 -0.4636485   0.22524291  0.79788231]
 [ 0.87221236  0.46869526  0.10023215 -0.0975903 ]]


### Answer/Commentary:
Our Q only contains one of the normalized eigenvectors. B also contains the eigenvalues on the main diagonal,
however this time not all other entries are zero, instead we end up with the Schur decomposition.

## c.
Can you use your function to find SVD to the matrix $A$ in task 1, without explicitly
forming $A^TA$ and $AA^T$? If so, try it out!
Switch off the last two lines in the algorithm (“print B” and “choose if
convergence…”), and let the loop run for example 100 iterations. Try to see what
kind of structure you get in the result.

In [22]:
def taskC(B):
    iterations = 100
    converged = False
    Q = np.identity(B.shape[0]) 
    while not converged:
        Q_temp, R = np.linalg.qr(B)
        B_new = R @ Q_temp
        Q = Q @ Q_temp
        if iterations > 100: # New modification for c
            converged = True
        B = B_new
        iterations += 1
    return B, Q

In [23]:
B, Q = taskC(A)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)

In [ ]:
Q, R = np.linalg.qr(A, mode="reduced")
print(Q)
print(R)

### Answer/Commentary
I assume that this was supposed to work in some fashion, but there seems to be an issue with the dimensions
in the matrix multiplications of the algorithm since A is not a square matrix and I'm not sure how to get around this, or if I am missing something. I tried a few different ways of altering the original algorithm after the first one did not work but I couldn't work it out without potentially changing the algorithm drastically, which I assume was not the point.